apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "55"
spec:
  project: homelab-dev
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-workflows
      targetRevision: 0.45.12
      helm:
        releaseName: argo-workflows
        valueFiles:
          - $values/apps/infrastructure/argo-workflows/overlays/dev/values.yaml
    - repoURL: git@github.com:awesomejt/homelab-k3s.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true