apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  project: homelab-dev
  sources:
    - repoURL: https://kubernetes-sigs.github.io/external-dns/
      chart: external-dns
      targetRevision: 1.18.0
      helm:
        releaseName: external-dns
        valueFiles:
          - $values/apps/infrastructure/external-dns/overlays/dev/values.yaml
    - repoURL: git@github.com:awesomejt/homelab-k3s.git
      targetRevision: main
      ref: values
    - repoURL: git@github.com:awesomejt/homelab-k3s.git
      targetRevision: main
      path: apps/infrastructure/external-dns/base
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true