apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - project.yaml
  - argocd-config.yaml
  - traefik-config.yaml
  - metrics-server-config.yaml
  - cert-manager-controller.yaml
  - cert-manager-issuers.yaml
  - metallb-controller.yaml
  - metallb-config.yaml
  - external-dns.yaml
  - reloader.yaml
  - longhorn.yaml
  - headlamp.yaml
  - argo-workflows.yaml
  - kube-prometheus-stack.yaml
  - sealed-secrets.yaml
  - descheduler.yaml
  - node-problem-detector.yaml