apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "25"
spec:
  project: homelab-dev
  sources:
    - repoURL: https://charts.longhorn.io
      chart: longhorn
      targetRevision: 1.7.2
      helm:
        releaseName: longhorn
        valueFiles:
          - $values/apps/infrastructure/longhorn/overlays/dev/values.yaml
    - repoURL: git@github.com:awesomejt/homelab-k3s.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true