apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-config-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: homelab-dev
  source:
    repoURL: git@github.com:awesomejt/homelab-k3s.git
    targetRevision: main
    path: apps/infrastructure/metallb-config/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true