apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "58"
spec:
  project: homelab-dev
  sources:
    - repoURL: https://bitnami-labs.github.io/sealed-secrets
      chart: sealed-secrets
      targetRevision: 2.17.2
      helm:
        releaseName: sealed-secrets
        valueFiles:
          - $values/apps/infrastructure/sealed-secrets/overlays/dev/values.yaml
    - repoURL: git@github.com:awesomejt/homelab-k3s.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true