apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  project: homelab-prod
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    chart: external-dns
    targetRevision: 1.18.0
    helm:
      releaseName: external-dns
      values: |
        provider:
          name: rfc2136
        policy: upsert-only
        registry: txt
        txtOwnerId: homelab-prod
        sources:
          - service
          - ingress
        domainFilters:
          - taylor.lan
        extraArgs:
          - --rfc2136-host=dns.taylor.lan
          - --rfc2136-port=53
          - --rfc2136-zone=taylor.lan
          - --rfc2136-insecure
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true