apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "35"
spec:
  project: homelab-prod
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 61.3.1
    helm:
      values: |
        grafana:
          admin:
            existingSecret: "grafana-admin"
            userKey: "admin-user"
            passwordKey: "admin-password"
          ingress:
            enabled: true
            ingressClassName: traefik
            hosts:
              - grafana.prod.lab
            tls:
              - secretName: grafana-tls
                hosts:
                  - grafana.prod.lab
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-lab
        prometheus:
          ingress:
            enabled: true
            ingressClassName: traefik
            hosts:
              - prometheus.prod.lab
            tls:
              - secretName: prometheus-tls
                hosts:
                  - prometheus.prod.lab
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-lab
        alertmanager:
          ingress:
            enabled: true
            ingressClassName: traefik
            hosts:
              - alertmanager.prod.lab
            tls:
              - secretName: alertmanager-tls
                hosts:
                  - alertmanager.prod.lab
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-lab
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated: