apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - project.yaml
  - metallb-controller.yaml
  - metallb-config.yaml
  - external-dns.yaml
  - harbor.yaml
  - headlamp.yaml
  - reposilite.yaml
  - kube-prometheus-stack.yaml