apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: homelab-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Homelab prod cluster applications
  sourceRepos:
    - git@github.com:awesomejt/homelab-k3s.git
    - https://metallb.github.io/metallb
    - https://kubernetes-sigs.github.io/external-dns/
    - https://helm.goharbor.io
    - https://github.com/kubernetes-retired/dashboard.git
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'