apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-config-stage
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: homelab-stage
  source:
    repoURL: git@github.com:awesomejt/homelab-k3s.git
    targetRevision: main
    path: apps/infrastructure/argocd/overlays/stage
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
