apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-issuers-stage
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  project: homelab-stage
  source:
    repoURL: git@github.com:awesomejt/homelab-k3s.git
    targetRevision: main
    path: apps/infrastructure/cert-manager-issuers/base
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated: