apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor-stage
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "40"
spec:
  project: homelab-stage
  source:
    repoURL: https://helm.goharbor.io
    chart: harbor
    targetRevision: 1.18.0
    helm:
      releaseName: harbor
      values: |
        expose:
          type: ingress
          tls:
            enabled: true
            certSource: auto
          ingress:
            className: traefik
            hosts:
              core: harbor.stage.lab
        externalURL: https://harbor.stage.lab
        updateStrategy:
          type: Recreate
        persistence:
          enabled: true
          persistentVolumeClaim:
            registry:
              storageClass: local-path
              size: 20Gi
            jobservice:
              jobLog:
                storageClass: local-path
                size: 2Gi
            database:
              storageClass: local-path
              size: 2Gi
            redis:
              storageClass: local-path
              size: 2Gi
            trivy:
              storageClass: local-path
              size: 5Gi
        existingSecretAdminPassword: harbor-admin-credentials
        existingSecretAdminPasswordKey: HARBOR_ADMIN_PASSWORD
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true