apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack-stage
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "35"
spec:
  project: homelab-stage
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 61.3.1
    helm:
      valueFiles:
        - values.yaml
      values: |
        grafana:
          admin:
            existingSecret: "grafana-admin"
            userKey: "admin-user"
            passwordKey: "admin-password"
          ingress:
            enabled: true
            ingressClassName: traefik
            hosts:
              - grafana-stage.taylor.lan
            tls:
              - secretName: grafana-stage-tls
                hosts:
                  - grafana-stage.taylor.lan
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
        prometheus:
          ingress:
            enabled: true
            ingressClassName: traefik
            hosts:
              - prometheus-stage.taylor.lan
            tls:
              - secretName: prometheus-stage-tls
                hosts:
                  - prometheus-stage.taylor.lan
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
        alertmanager:
          ingress:
            enabled: true
            ingressClassName: traefik
            hosts:
              - alertmanager-stage.taylor.lan
            tls:
              - secretName: alertmanager-stage-tls
                hosts:
                  - alertmanager-stage.taylor.lan
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated: