apiVersion: ENC[AES256_GCM,data:B/g=,iv:yIwOS4neisb4b31UdbWkIN5Oa/WKxMIDzBOuG65VGZQ=,tag:7I0GCfeYJNE8uDGGopYv5w==,type:str]
kind: ENC[AES256_GCM,data:ZustoSMA,iv:fMJr4AC4Dk9H2b3d29RZy9Y4dMDtkP3ZQJ9+XuLCEFw=,tag:cgfJqQJMUfdQaOq3YP2mSQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:pF5vOqLrUKJSMD3OCg==,iv:9rpB/Ho1X663xEB4UCVN2ahpwPi0pXd8Iav6EcA+vdk=,tag:kicUu5Dc7yX/UBwJYMM0HA==,type:str]
    namespace: ENC[AES256_GCM,data:j2N3VCRHMWYe5w==,iv:S3X4VXz648rpeqTScTqtK7og7pvsrRpPLIUIvvlBsmM=,tag:hnuBEOqe+7dPuoGkQoD2sw==,type:str]
type: ENC[AES256_GCM,data:1OHUgicg,iv:hIp8spSZwSf7QhBZcGA+4T4n7VJeFScvR/e+IAZBxSA=,tag:ZrfaDx4/CZzm87TpTchmnQ==,type:str]
stringData:
    admin-password: ENC[AES256_GCM,data:r9ddqJ8fSoRm,iv:RSbPNiY+Z63xXCR51dAksg6JeanqS+R0ImTJZif8FSY=,tag:5FgBfId5YPCdZ9miCmn21A==,type:str]
sops:
    age:
        - recipient: age1hsjjjnyycyz2r2c4rm9zkctcm0wz9nm4pwcq0ka5pzpypvthxfaqgqn888
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxMXBTVGkwYlQvcjZKamRI
            WENHb2RnL1lZbjFweVVkWTdJMWhjMmw3SUc4CnR6VG1UQmlwQ09XeGFwbEFmOGd2
            VGhpYlJBeGJnTDdTQ1pCbUR4ZEE1YmcKLS0tIDBUeFhHZ0FlR0NhOTYvK1FqaG5Y
            TS80S0pSaVRBSXNWODJPV1pUUzhPSFEKLj1Tx2pNlmINFyRrMQWDh22imDTKiGaO
            7U2KyvPv4fsM0d3nHg0hpy3GkkwA69ta/G7v9IfZd/C2/c+rrr0oYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T04:30:18Z"
    mac: ENC[AES256_GCM,data:UVnJM1w4yi1RIJDf8nAx5OEYPENje+pXzbd3oRkm2VJjvZairMMvGTIlaiwJXSwrqq1tzqnlBlM2STJEPrBNDDySFSlt3e1CUwNmy8SenRbxYQ/xu2MbD2tRXwAevLZNvdu0hpU/Qc+7ZEZJvoTD9SFxov2IKOILoPGgIAJ4+yk=,iv:RCfXKtT4n3yNEKMX65M3zYHtmrvGbmXB1MMKY4tfGUU=,tag:DMC8IMSA5PKF7hw9N5mAPQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
