apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    providers:
      kubernetesIngress:
        publishedService:
          enabled: true
    ingressClass:
      enabled: true
      isDefaultClass: true
    logs:
      general:
        level: INFO