apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: reposilite
spec:
  tls:
  - hosts:
    - artifacts-prod.taylor.lan
    secretName: artifacts-prod-tls
  rules:
  - host: artifacts-prod.taylor.lan