apiVersion: apps/v1
kind: Deployment
metadata:
  name: reposilite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reposilite
  template:
    metadata:
      labels:
        app: reposilite
    spec:
      containers:
      - name: reposilite
        image: dzikoysk/reposilite:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: data
          mountPath: /app/data
        env:
        - name: REPOSILITE_OPTS
          value: "--port=8080"
        - name: REPOSILITE_USERNAME
          valueFrom:
            secretKeyRef:
              name: reposilite-admin
              key: username
        - name: REPOSILITE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: reposilite-admin
              key: password
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: reposilite-data