apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  taylor.lan.server: |
    taylor.lan:53 {
        errors
        cache 30
        forward . 192.168.50.53
    }
