grafana:
  admin:
    existingSecret: "grafana-admin"
    userKey: "admin-user"
    passwordKey: "admin-password"
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - grafana.prod.lab
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.prod.lab
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-lab

prometheus:
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - prometheus.prod.lab
    tls:
      - secretName: prometheus-tls
        hosts:
          - prometheus.prod.lab
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-lab

alertmanager:
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - alertmanager.prod.lab
    tls:
      - secretName: alertmanager-tls
        hosts:
          - alertmanager.prod.lab
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-lab