apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-rfc2136
  namespace: external-dns
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: external-dns-rfc2136
    creationPolicy: Owner
  data:
    - secretKey: tsig-keyname
      remoteRef:
        key: secret/k3s/dev/external-dns-tsig
        property: tsig-keyname
    - secretKey: tsig-secret
      remoteRef:
        key: secret/k3s/dev/external-dns-tsig
        property: tsig-secret
    - secretKey: tsig-secret-alg
      remoteRef:
        key: secret/k3s/dev/external-dns-tsig
        property: tsig-secret-alg
