apiVersion: ENC[AES256_GCM,data:hn4=,iv:6Ik5CU/YSR3vPI7dzuQWHn5R2haX1csFuH3ebEAgLOg=,tag:9J0fEXLf2ijNG21cZBkjGg==,type:str]
kind: ENC[AES256_GCM,data:fj6AnQX8,iv:FvRY+newp9Oz1aqA1AhIEFVVxaHX/zGy3t0SpZXPRcA=,tag:Btpf0RulYpWfbTMzwMzTQw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:NGtBJJel6RhTNNmAMapG38/An+E=,iv:9u3s63LbXn6xOTs0H8Le/xpcBMlPUlVWsmxTpXEEhq4=,tag:UYOSee1pscmLqJTxE10Ahg==,type:str]
    namespace: ENC[AES256_GCM,data:F1rlgXJOJHPnXfQ2,iv:3dBqguIhjjBia8Dk/EXjaPlztca/M2SqCTdOrjkaQTs=,tag:osEoOdAZ0icVQUbu6RBPtA==,type:str]
type: ENC[AES256_GCM,data:rwGYDTsw,iv:nj4qNpL6GfkdJrZgP/ICyYXX9YDncxiPaynRdzC8/Ks=,tag:yOVkkYm2BQFtfUn6LEgetA==,type:str]
stringData:
    tsig-secret: ENC[AES256_GCM,data:3qXqHJUjZabCpM66ygByOK85dVnJ35ykexmy/1Nolebc5ANdT4wa5E5XsYAlWNfzIVzmTveuvI+tgHYA64w9tJJLCdov8ra26Woy94rzhwegMsLaTOw=,iv:qX288tAfSVVsawKKakRzyDiZoIJlQlJGVrLZZ66plqk=,tag:UK4SaoNVqcwYufPmL2cjMA==,type:str]
    tsig-keyname: ENC[AES256_GCM,data:PRC5dVB35xloJAhE1ytIIwg=,iv:LJcgtlDCKBdjJ/fT9VKS2bKC6yEmGd5UzM1gUQDUZhE=,tag:vlhfy0n/a8exkUApZPl40g==,type:str]
sops:
    age:
        - recipient: age1hsjjjnyycyz2r2c4rm9zkctcm0wz9nm4pwcq0ka5pzpypvthxfaqgqn888
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIS3o4TmpDeGk4MERLS1dB
            OTduNjJUR0JoVzhhZ0lQWG1BdUZlV25PN2tvClFCQllHcmtCcTVxNDZadXhKUk1I
            MmVCcGl1VmlIS1JXVms4Yi9wOWx2djgKLS0tIDcvY2ZCSlRnS0lUdlp6cDNtVWd1
            MWVaSjF6WVVHTGMwcGI2eit6OUlFWTgKTd7RplSkOTEAVLrii/baiWz5WcMaMFja
            IkXOFtVPmhvGFEGD5yKVxc7F3QWbiQ3ZNAivL1ZCYUNw4MMYwXAR8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T04:01:59Z"
    mac: ENC[AES256_GCM,data:6iOYY7S9dPhu+a6/K3rizbXYUWNlgwfh/l9PJiVIjzfLNZymgXW21+FEyJL383qvlfz7aOz/0AYwJWatuLRHKt1nDcnaxy2YXuf3CMPwOquyyO6UaAt6JigggFGZLQZuBI7NVIoaH9pIcxx1RNiR1lW98OKUBfrV3kzPHYwCYKQ=,iv:wKaBTHzqulNqDF3jEDEf/qturZ+tsZT+8qgrPF+K3B0=,tag:7cp4r9hHxcq08LR/0QXh4Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
